#spring.application.name=bamoe test


# ===============================
# Spring Application
# ===============================
spring.application.name=loan-approval-workflow

# ===============================
# JPA Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ===============================
# Datasource (H2)
# ===============================
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# H2 Console
# ===============================
spring.h2.console.enabled=true

# ===============================
# Kogito Configuration
# ===============================
kogito.service.url=http://localhost:8080
kogito.processes.enabled=true
kogito.decisions.enabled=false

kogito.data-index.url=http://localhost:8180
kogito.data-index.username=
kogito.data-index.password=

# ===============================
# Server Config
# ===============================
server.port=8080
server.servlet.context-path=/api

# Static resources
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/static/**